language: php

php:
- 7.1

before_script:
- composer self-update
- composer install --no-interaction
- composer require nikic/php-parser
- composer require "laravelcollective/html":"^5.4.0"
- php artisan config:clear
- php artisan cache:clear
- php artisan config:cache